name: Deploy flask App

on: workflow_dispatch

jobs:
    deploy:
        environment:
            DOCKERHUB_USER: ${{ vars.DOCKERHUB_USER }}
        runs-on: self-hosted
        steps:
            - name: code checkout
              uses: actions/checkout@v5

            - name: Deploy with docker_compose
              run: docker compose up -d --build
