name: hello

on: workflow_dispatch

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: say hello
        run: echo "hi how are you , i am find" > hello.txt
      - name: show the content of hello.txt
        run: cat hello.txt
