name: practice1

on: workflow_dispatch

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: hello to the user
              run: echo "Hello how are you" > hello.txt

            - name: see what message send me
              run: cat hello.txt

            - name: file create
              run: touch file.txt

    test:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: user information
              run: echo "Who are you $USER"

            - name: hostname
              run: echo "My hostname is $(hostname -I)"

            - name: show what is the version of python & docker etc
              run: docker --version && python --version
